---
title: "Instalando RStudio en Ubuntu Bionic 64-bit"
author: "Francisco Rivas"
date: "5/19/2020"
output: 
  html_document:
    theme: united  
    highlight: kate 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Preambulo
Este documento fue elaborado con **rmarkdown_2.1** y compilado con **knitr_1.28** en **RStudio Desktop 1.2.5033 "Orange Blossom"**.

Los enlaces están actualizados al **`r Sys.Date()`**.

## Introducción
Si acabas de instalar **Ubuntu 18.04 LTS** y necesitas tener listo RStudio para comenzar a trabajar, utiliza esta pequeña guía para que no des tantas vueltas en la web. Sólo tienes que ejecutar linea a linea los bloques de código que te mostraré a continuación y en poco tiempo ya tendrás todo el software instalado.

## Instalando R {.tabset .tabset-fade}
### R 3.6

```bash
# Puedes omitir la primera linea si lo deseas
sudo printf "# Repositorio R 3.6 Ubuntu Bionic" >> /etc/apt/sources.list
sudo printf "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" >> /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo apt-get update
sudo apt-get install r-base r-base-dev
```
### R 4.0

```bash
# Puedes omitir la primera linea si lo deseas
sudo printf "# Repositorio R 4.0 Ubuntu Bionic" >> /etc/apt/sources.list 
sudo printf "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/" >> /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
sudo apt-get update
sudo apt-get install r-base r-base-dev
```
#
Verifica que la instalación se realizó correctamente ejecutando `R --version` en el terminal.

## Instalando RStudio Desktop
Las siguientes lineas de código instalaran RStudio Desktop 1.2.5042 en tu OS.

```bash
# El primer comando es importante para que el paquete descargado quede en un lugar conocido
cd ~/Downloads
nombre_archivo="rstudio-1.2.5042-amd64.deb"
URL="https://download1.rstudio.org/desktop/bionic/amd64/$nombre_archivo"
wget -nv --show-progress $URL

sudo chmod +x "$nombre_archivo"
sudo dpkg -i "$nombre_archivo"
```

### ¡ATENCIÓN! 
Si detienes la descarga, un archivo con el nombre "rstudio-1.2.5042-amd64.deb" se creará en el directorio de trabajo actual (~/Downloads). Esto puede llegar a confundirte ya que la próxima vez que intentes descargar el paquete, este se guardará como "rstudio-1.2.5042-amd64.deb**1**" para evitar conflicto con el archivo que ya existe.
